// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTH_SESSIONS: KVNamespace;
	RESEND_API_KEY: string;
	GEMINI_API_KEY: string;
	GROQ_API_KEY: string;
	DB: D1Database;
	CLUB_FILES: R2Bucket;
	BLOG_IMAGES: R2Bucket;
	CASE_STUDIES: R2Bucket;
	GALLERY_CDN: R2Bucket;
	QUEUE: Queue;
}
